version: '3.8'

services:
  web:
    build: .
    container_name: pdpa-web
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=pdpa_db
      - DB_USER=pdpa_user
      - DB_PASS=pdpa_pass
    networks:
      - pdpa-network

  db:
    image: mysql:8.0
    container_name: pdpa-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: pdpa_db
      MYSQL_USER: pdpa_user
      MYSQL_PASSWORD: pdpa_pass
    volumes:
      - db-data:/var/lib/mysql
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - pdpa-network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: pdpa-phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_USER: pdpa_user
      PMA_PASSWORD: pdpa_pass
    depends_on:
      - db
    networks:
      - pdpa-network

volumes:
  db-data:

networks:
  pdpa-network:
    driver: bridge
